@baseUrl = http://localhost:8080
@email = user@mail.com
@password = Password123

### Signup
POST {{baseUrl}}/auth/signup
Content-Type: application/json
Accept: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

### Login
POST {{baseUrl}}/auth/login
Content-Type: application/json
Accept: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

> {%
client.global.set("token", response.body.token);
client.global.set("userId", String(response.body.userId));
%}
