@baseUrl = http://localhost:8080
@profileId = 1

### Get profile by profile id (public)
GET {{baseUrl}}/profiles/{{profileId}}
Accept: application/json

### Update my profile (must match token owner profile)
PUT {{baseUrl}}/profiles/{{profileId}}
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
  "fullName": "John Doe",
  "bio": "Software engineer"
}

### Delete my profile (must match token owner profile)
DELETE {{baseUrl}}/profiles/{{profileId}}
Authorization: Bearer {{token}}
Accept: application/json
